# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CharlieCli < Formula
  desc "AI-native autonomous development orchestrator"
  homepage "https://github.com/cclss/charlie-cli"
  version "2.2.29"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cclss/charlie-cli-releases/releases/download/v2.2.29/charlie_2.2.29_darwin_amd64.tar.gz"
      sha256 "b927766d86455459884e0992c252c9ee62f7ff1012c6c0a8a739b60b508c8f6e"

      define_method(:install) do
        bin.install "charlie"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cclss/charlie-cli-releases/releases/download/v2.2.29/charlie_2.2.29_darwin_arm64.tar.gz"
      sha256 "c9a6a573b7ac4eb14e6273197800aa5a5d16ce9eec73b13704f3cf2006d4daa9"

      define_method(:install) do
        bin.install "charlie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cclss/charlie-cli-releases/releases/download/v2.2.29/charlie_2.2.29_linux_amd64.tar.gz"
      sha256 "3ddc88e9ff787b741d56ef0ff8b57e64cbb063df58adcc6843d71e62c65d267d"
      define_method(:install) do
        bin.install "charlie"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cclss/charlie-cli-releases/releases/download/v2.2.29/charlie_2.2.29_linux_arm64.tar.gz"
      sha256 "7d7c3a29fea514439a93aab16b414b421f8ceebe64598b39df7f63eb178e9718"
      define_method(:install) do
        bin.install "charlie"
      end
    end
  end

  test do
    system "#{bin}/charlie", "--version"
  end
end
