# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CharlieCliReleases < Formula
  desc "AI-native autonomous development orchestrator"
  homepage "https://github.com/cclss/charlie-cli"
  version "0.1.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cclss/charlie-cli-releases/releases/download/v0.1.0/charlie_0.1.0_darwin_amd64.tar.gz"
      sha256 "fad4e604b959aea1b99826177194d0aef02e89eea09118c3bdd4bc4241b2d4ef"

      define_method(:install) do
        bin.install "charlie"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cclss/charlie-cli-releases/releases/download/v0.1.0/charlie_0.1.0_darwin_arm64.tar.gz"
      sha256 "bc0d774c234698daf6b1baef7d44e4aacf712e319fd11500b5a0d3719b067f7b"

      define_method(:install) do
        bin.install "charlie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cclss/charlie-cli-releases/releases/download/v0.1.0/charlie_0.1.0_linux_amd64.tar.gz"
      sha256 "ff418e550f5da6118b265579b00e87ed2046ecfc02ad298826f5e501e08542e1"
      define_method(:install) do
        bin.install "charlie"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cclss/charlie-cli-releases/releases/download/v0.1.0/charlie_0.1.0_linux_arm64.tar.gz"
      sha256 "bd7d20e51b1dee31caeb8a79656852c76f3e998d678c6e14e669c0f3139b7c53"
      define_method(:install) do
        bin.install "charlie"
      end
    end
  end

  test do
    system "#{bin}/charlie", "--version"
  end
end
