# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CharlieCli < Formula
  desc "AI-native autonomous development orchestrator"
  homepage "https://github.com/cclss/charlie-cli"
  version "0.5.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cclss/charlie-cli-releases/releases/download/v0.5.0/charlie_0.5.0_darwin_amd64.tar.gz"
      sha256 "9bc692d5e2a570a9ddca28e6977faa2299211c1e75cee1ac39977e1907b5a290"

      define_method(:install) do
        bin.install "charlie"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cclss/charlie-cli-releases/releases/download/v0.5.0/charlie_0.5.0_darwin_arm64.tar.gz"
      sha256 "9d52d5597d522409be773fc0ea65c20a6ed3169227d0c689d1b11d0dccd24b25"

      define_method(:install) do
        bin.install "charlie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cclss/charlie-cli-releases/releases/download/v0.5.0/charlie_0.5.0_linux_amd64.tar.gz"
      sha256 "d4497d964af2b3f2725f5b92baeb48e3c846e9dbe0180233a3c8f5a1b8452af2"
      define_method(:install) do
        bin.install "charlie"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cclss/charlie-cli-releases/releases/download/v0.5.0/charlie_0.5.0_linux_arm64.tar.gz"
      sha256 "3f8bf64399862c222f20d71c73b3b1d6817ac87815c2c9630a83d6d21f9e2d6c"
      define_method(:install) do
        bin.install "charlie"
      end
    end
  end

  test do
    system "#{bin}/charlie", "--version"
  end
end
