# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XRay < Formula
  desc "코드베이스를 분석해 .x-ray/ 지도를 생성하는 CLI 도구"
  homepage "https://github.com/cclss/x-ray-releases"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cclss/x-ray-releases/releases/download/v0.2.0/x-ray-releases_0.2.0_darwin_amd64.tar.gz"
      sha256 "35053647c4493534b5aeea951d63e51f04adc5e829845dacd2bbe3d7250d21ae"

      def install
        bin.install "x-ray"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cclss/x-ray-releases/releases/download/v0.2.0/x-ray-releases_0.2.0_darwin_arm64.tar.gz"
      sha256 "05d3a75641f7fc0bf215bdf26e4937950b4376f8766ca070af1983b5d4fdd467"

      def install
        bin.install "x-ray"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cclss/x-ray-releases/releases/download/v0.2.0/x-ray-releases_0.2.0_linux_amd64.tar.gz"
      sha256 "59025eb0bd12b856a6c22ed9d1b81e36a60b2096f896de7fa92a743b299e2444"
      def install
        bin.install "x-ray"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cclss/x-ray-releases/releases/download/v0.2.0/x-ray-releases_0.2.0_linux_arm64.tar.gz"
      sha256 "1437c59eabd0c666b53249b31be89710f942fbe2797445ba2d928c01b7d78f10"
      def install
        bin.install "x-ray"
      end
    end
  end

  test do
    system "#{bin}/x-ray", "version"
  end
end
